function slugify(input) {
  return String(input || "skillforge")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function slugifyCreator(name) {
  if (!name) return "@unknown";
  const slug = String(name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `@${slug || "unknown"}`;
}

function formatDate(isoString) {
  return new Date(isoString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function buildHeader(data) {
  return `# AI-Synthesized Knowledge: ${data.topic}
> Generated by SkillForge from ${data.source_count} YouTube videos on ${formatDate(
    data.generated_at
  )}`;
}

function renderBulletList(items) {
  return items.map((item) => `- ${item}`).join("\n");
}

function formatSkill(data) {
  const description = data.summary || `Synthesized YouTube knowledge about ${data.topic}.`;
  const usage = `Load this skill when working on ${data.topic} strategy, execution, or review tasks.`;

  const frameworks = data.frameworks
    .map((framework) => {
      const parts = [`### ${framework.name}`, framework.description];
      if (framework.steps?.length) {
        parts.push("### Steps", framework.steps.map((step, index) => `${index + 1}. ${step}`).join("\n"));
      }
      if (framework.source_titles?.length) {
        parts.push(`### Sources\n${renderBulletList(framework.source_titles)}`);
      }
      return parts.join("\n\n");
    })
    .join("\n\n");

  const tactics = data.tactics
    .map((tactic) =>
      [
        `### ${tactic.title}`,
        tactic.details,
        `When to use: ${tactic.when_to_use}`,
        tactic.source_titles?.length
          ? `Sources:\n${renderBulletList(tactic.source_titles)}`
          : null,
      ]
        .filter(Boolean)
        .join("\n\n")
    )
    .join("\n\n");

  const concepts = data.concepts
    .map((concept) => `- **${concept.term}**: ${concept.definition}`)
    .join("\n");

  const processes = data.processes
    .map((process) =>
      [
        `### ${process.name}`,
        process.steps?.map((step, index) => `${index + 1}. ${step}`).join("\n"),
        process.source_titles?.length
          ? `Sources:\n${renderBulletList(process.source_titles)}`
          : null,
      ]
        .filter(Boolean)
        .join("\n\n")
    )
    .join("\n\n");

  const quotes = data.quotes
    .map(
      (quote) =>
        `> ${quote.quote}\n>\n> ${quote.speaker || "Unknown"} on ${quote.context} (${quote.source_title})`
    )
    .join("\n\n");

  const frontmatter = [
    `---`,
    `name: "${data.topic}"`,
    `description: "${description.replace(/"/g, '\\"')}"`,
    `usage: "${usage.replace(/"/g, '\\"')}"`,
    `built_at: "${data.built_at || data.generated_at}"`,
  ];
  if (data.creator) {
    frontmatter.push(`creator: "${data.creator}"`);
    frontmatter.push(`creator_slug: "${data.creator_slug || slugifyCreator(data.creator)}"`);
  }
  if (data.topic_slug) {
    frontmatter.push(`topic: "${data.topic_slug}"`);
  }
  if (data.last_updated) {
    frontmatter.push(`last_updated: "${data.last_updated}"`);
  }
  if (data.source_videos?.length) {
    frontmatter.push(`source_videos:`);
    for (const sv of data.source_videos) {
      if (typeof sv === "object" && sv.url) {
        frontmatter.push(`  - url: "${sv.url}"`);
        if (sv.date) frontmatter.push(`    date: "${sv.date}"`);
      } else {
        frontmatter.push(`  - url: "${sv}"`);
      }
    }
  }
  if (data.sources?.length) {
    frontmatter.push(`sources:`);
    for (const src of data.sources) {
      frontmatter.push(`  - "${src}"`);
    }
  }
  if (data.merged_from_channels?.length) {
    frontmatter.push(`merged_from_channels:`);
    for (const ch of data.merged_from_channels) {
      frontmatter.push(`  - "${ch}"`);
    }
  }
  frontmatter.push(`---`);

  return `${frontmatter.join("\n")}

${buildHeader(data)}

## Summary

${description}

## Frameworks

${frameworks || "No frameworks were extracted."}

## Tactics

${tactics || "No tactics were extracted."}

## Core Concepts

${concepts || "No core concepts were extracted."}

## Processes

${processes || "No processes were extracted."}

## Key Quotes

${quotes || "No quotes were extracted."}
`;
}

function formatMarkdown(data) {
  const frameworks = data.frameworks
    .map((framework) =>
      [
        `### ${framework.name}`,
        framework.description,
        framework.steps?.length
          ? framework.steps.map((step, index) => `${index + 1}. ${step}`).join("\n")
          : null,
      ]
        .filter(Boolean)
        .join("\n\n")
    )
    .join("\n\n");

  const tactics = data.tactics
    .map((tactic) =>
      [
        `### ${tactic.title}`,
        tactic.details,
        `When to use: ${tactic.when_to_use}`,
      ]
        .filter(Boolean)
        .join("\n\n")
    )
    .join("\n\n");

  const concepts = data.concepts
    .map((concept) => `- **${concept.term}**: ${concept.definition}`)
    .join("\n");

  const quotes = data.quotes
    .map(
      (quote) =>
        `> ${quote.quote}\n>\n> ${quote.speaker || "Unknown"} (${quote.source_title})`
    )
    .join("\n\n");

  const fullNotes = data.full_notes.map((note) => `- ${note}`).join("\n");

  return `${buildHeader(data)}

## Key Takeaways

${data.summary}

## Frameworks

${frameworks || "No frameworks were extracted."}

## Tactics

${tactics || "No tactics were extracted."}

## Key Quotes

${quotes || "No quotes were extracted."}

## Core Concepts

${concepts || "No concepts were extracted."}

## Full Notes

${fullNotes || "No additional notes were extracted."}
`;
}

function formatJson(data) {
  return JSON.stringify(
    {
      topic: data.topic,
      source_count: data.source_count,
      frameworks: data.frameworks,
      tactics: data.tactics,
      quotes: data.quotes,
      concepts: data.concepts,
      processes: data.processes,
      full_notes: data.full_notes,
    },
    null,
    2
  );
}

function formatDocument(format, data) {
  if (format === "skill") {
    return formatSkill(data);
  }

  if (format === "markdown") {
    return formatMarkdown(data);
  }

  if (format === "json") {
    return formatJson(data);
  }

  throw new Error(`Unsupported format: ${format}`);
}

function makeOutputFilename(format, topicSlug) {
  if (format === "skill") {
    return pathJoinSafe(topicSlug, "SKILL.md");
  }

  if (format === "markdown") {
    return `${topicSlug}.md`;
  }

  if (format === "json") {
    return `${topicSlug}.json`;
  }

  throw new Error(`Unsupported format: ${format}`);
}

function pathJoinSafe(...parts) {
  return parts.join("/");
}

export {
  formatDocument,
  makeOutputFilename,
  slugify,
  slugifyCreator,
};
